apiVersion: v1
kind: ConfigMap
metadata:
  name: user-service-config
data:
  DB_URL: "jdbc:postgresql://postgres-users:5432/users"
  DB_USER: "cinetrack"
  EUREKA_URI: "http://eureka-server:8761/eureka"
