apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cinetrack-eu-west

resources:
  - ../../base/eureka-server
  - ../../base/api-gateway
  - ../../base/catalog-service
  - ../../base/user-service
  - ../../base/watchlist-service
  - ../../base/review-service
  - ../../base/notification-service
  - ../../base/recommendation-service
  - ../../base/kafka

patches:
  - patch: |-
      - op: replace
        path: /data/KAFKA_BOOTSTRAP
        value: kafka-eu-west:9092
    target:
      kind: ConfigMap
      name: review-service-config

images:
  - name: cinetrack/catalog-service
    newTag: eu-latest
