apiVersion: v1
kind: ConfigMap
metadata:
  name: recommendation-service-config
data:
  REDIS_HOST: "redis:6379"
  KAFKA_BOOTSTRAP: "kafka:9092"
  EUREKA_URI: "http://eureka-server:8761/eureka"
  AUTH_SERVER_JWKS_URI: "http://user-service:8082/oauth2/jwks"
