apiVersion: v1
kind: ConfigMap
metadata:
  name: watchlist-service-config
data:
  DB_URL: "jdbc:postgresql://postgres-watchlist:5432/watchlist"
  DB_USER: "cinetrack"
  EUREKA_URI: "http://eureka-server:8761/eureka"
  AUTH_SERVER_JWKS_URI: "http://user-service:8082/oauth2/jwks"
